In [8]:
import sys
sys.path.insert(0, 'C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts')
from Libs import *
from sklearn import preprocessing

#########

# Intersection_DF no devuelvo nada.. No se si sirve esto.

In [6]:
conflict_df = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/ConflictDB/df_conflicto.csv', index_col=0)

programs_df = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/ForeignAssProgDB/df_total.csv', index_col=0)

trade_df =  pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/TradeDB/TradeClean.csv', index_col=0)

conflict_df.rename(columns= {'location':'country'}, inplace=True)
trade_df.rename(columns= {'Recipient':'country', 'Year Weapon of order': 'year'}, inplace=True)
conflict_df.drop_duplicates(inplace=True)

In [7]:
df_part1 = pd.merge(conflict_df, programs_df, on=['country', 'year'], how='outer', left_index=False, right_index=False)
df_part2 = pd.merge(df_part1, trade_df, on=['country', 'year'], how='outer', left_index=False, right_index=False)

df_final = pd.merge(df_part1, df_part2, on=['country', 'year', 'amount'], how='outer', left_index=False, right_index=False)
df_final = df_final.drop_duplicates()
df_final['conflict'] = False

In [4]:
country_conflicto = conflict_df['country'].unique()

In [5]:
for x in country_conflicto:
    year = conflict_df[conflict_df['country'] == x]['year']
    for i in year:
        df_final.loc[(df_final['country'] == x) & (df_final['year'] == i), 'conflict'] = True

In [6]:
df_final['Tools'].fillna(0, inplace=True)
df_final['Vehicles'].fillna(0, inplace=True)
df_final['Weapons'].fillna(0, inplace=True)

In [7]:
country_df_final = df_final['country'].unique()

In [8]:
df_final['conflict-1-to-3'] = np.nan
df_final['conflict-4-to-6'] = np.nan
df_final['conflict-7-to-9'] = np.nan
df_final['Prom USA'] = np.nan

In [9]:
for c in country_df_final:
    for x in range(1940, 2018):
        
        yearw_3 = 0
        yearw_2 = 0
        yearw_1 = 0
        prom_w = 0

        yearv_3 = 0
        yearv_2 = 0
        yearv_1 = 0
        prom_v = 0

        yeart_3 = 0
        yeart_2 = 0
        yeart_1 = 0
        prom_t = 0

        yearp_3 = 0
        yearp_2 = 0
        yearp_1 = 0
        prom_p = 0

        # weapons
        try:
            yearw_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Weapons'].item()
        except:
            yearw_3 = 0
        try:
            yearw_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Weapons'].item()
        except:
            yearw_2 = 0
        try:
            yearw_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Weapons'].item()
        except:
            yearw_1 = 0

        prom_w = (yearw_3 + yearw_2 + yearw_1) / 3

        # Vehicles
        try:
            yearv_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Vehicles'].item()
        except:
            yearv_3 = 0

        try:
            yearv_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Vehicles'].item()
        except:
            yearv_2 = 0

        try:
            yearv_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Vehicles'].item()
        except:
            yearv_1 = 0

        prom_v = (yearv_3 + yearv_2 + yearv_1) / 3

        # Tools
        try:
            yeart_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Tools'].item()
        except:
            yeart_3 = 0

        try:
            yeart_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Tools'].item()
        except:
            yeart_2 = 0

        try:
            yeart_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Tools'].item()
        except:
            yeart_1 = 0


        prom_t = (yeart_3 + yeart_2 + yeart_1) / 3
        
        # PROM USA
        try:
            yearp_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].item()
        except:
            yearp_3 = 0

        try:
            yearp_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].item()
        except:
            yearp_2 = 0

        try:
            yearp_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].item()
        except:
            yearp_1 = 0

        prom_p = (yearp_3 + yearp_2 + yearp_1) / 3
            
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Tools'] = prom_t
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Vehicles'] = prom_v
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Weapons'] = prom_w
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom USA'] = prom_p

In [10]:
for c in country_df_final:
    for x in range(1940, 2019):  


            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-4)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-5)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-6)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-7)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-8)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-9)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            #try:
                #    if(df_final[(df_final['country'] == c) & (df_final['year'] == x-10)]['conflict'].item()):
                #        df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            #except:
                #    pass

In [11]:
df_final.head()

,year,country,amount,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,conflict,conflict-1-to-3,conflict-4-to-6,conflict-7-to-9,Prom USA
0,1946,Bolivia,nan,0.00,0.00,0.00,0.00,0.00,0.00,True,NaN,NaN,NaN,0.00
1,1952,Bolivia,nan,0.00,0.00,0.00,0.00,0.00,0.00,True,NaN,True,NaN,0.00
2,1967,Bolivia,nan,0.00,53.00,24.00,0.00,9.33,0.00,True,NaN,NaN,NaN,nan
3,1946,Cambodia,nan,0.00,0.00,0.00,0.00,0.00,0.00,True,NaN,NaN,NaN,0.00
4,1947,Cambodia,nan,0.00,0.00,0.00,0.00,0.00,0.00,True,True,NaN,NaN,nan

In [10]:
encoder = preprocessing.LabelEncoder()
encoder.fit(df_final['country'].unique())

LabelEncoder()

In [11]:
countries_total = df_final['country']
countries_total_encoded = encoder.transform(countries_total)

In [12]:
len(countries_total_encoded)

9031

In [ ]:
df_f