In [140]:
import sys
sys.path.insert(0, 'C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts')
from Libs import *
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
#########

# Intersection_DF no devuelvo nada.. No se si sirve esto.

In [91]:
conflict_df = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/ConflictDB/df_conflicto.csv', index_col=0)

programs_df = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/ForeignAssProgDB/df_total.csv', index_col=0)

trade_df =  pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/TradeDB/TradeClean.csv', index_col=0)

conflict_df.rename(columns= {'location':'country'}, inplace=True)
trade_df.rename(columns= {'Recipient':'country', 'Year Weapon of order': 'year'}, inplace=True)
conflict_df.drop_duplicates(inplace=True)
programs_df.drop_duplicates(inplace=True)
trade_df.drop_duplicates(inplace=True)

In [107]:
df_n1 = pd.merge(conflict_df, trade_df, on=['country', 'year'], how='outer')
df_final = pd.merge(df_n1, programs_df, on=['country', 'year'], how='outer')
df_final.drop_duplicates(inplace=True)

In [109]:
df_final['conflict'] = np.nan

In [110]:
df_final.drop(df_final[df_final['country'] == 'Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Africa and Europe Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'African Union'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Arabian Peninsula Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Asia and Near East Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'CENTCOM Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Caribbean Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central African Republic'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central America Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central and Eastern Europe Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'EUCOM Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'East Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'East Asia and Pacific Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'East and Southern Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Eastern Caribbean Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Eurasia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Europe Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Europe and Eurasia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'FYR'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Global'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Great Lakes Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Lake Chad Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Latin America Region'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Levant Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Latin America Region'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Middle East and North Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Palestinian Territories'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Panama Canal Area Military School'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'South Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'South Caucasus Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'South and Central Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southeast Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southern Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southern Cone Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southwest Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Sub-Saharan Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'UAE'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'UN Transitional Administration in East Timor'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Unknown recipient(s)'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'West Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'West and North Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Western Hemisphere Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Western Sahara'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'West and North Africa Regional'].index.tolist(), inplace=True)

In [111]:
df_final['country'] = df_final['country'].str.strip().str.replace('United States of America', 'United States').str.replace('Zimbabwe \(Rhodesia\)', 'Zimbabwe').str.replace('Yemen \(North Yemen\)', 'Yemen').str.replace('Viet Nam', 'Vietnam').str.replace('Vietnam \(North Vietnam\)', 'Vietnam').str.replace('The Gambia', 'Gambia').str.replace('Soviet Union', 'Russia').str.replace('South Vietnam', 'Vietnam').str.replace('South Yemen', 'Yemen').str.replace('South Sudan', 'Sudan').str.replace('St. Vincent and the Grenadines', 'Saint Vincent').str.replace('St. Kitts and Nevis', 'Saint Kitts and Nevis').str.replace('Rumania', 'Romania').str.replace('Northern Cyprus', 'Cyprus').str.replace('North Yemen', 'Yemen').str.replace('Madagascar \(Malagasy\)', 'Madagascar').str.replace('Macedonia \(FYROM\)', 'Macedonia').str.replace('Libya GNC', 'Libya').str.replace('Libya HoR', 'Libya').str.replace('Ivory Coast', "Cote d'Ivoire").str.replace('Germany \(FRG\)', 'Germany').str.replace('East Germany \(GDR\)', 'Germany').str.replace('DR Congo \(Zaire\)', 'Congo').str.replace('DR Congo', 'Congo').str.replace('Bosnia-Herzegovina', 'Bosnia and Herzegovina').str.replace('Yemen \(Yemen\)', 'Yemen').str.replace('Congo \(Zaire\)', 'Congo').str.replace('Hong Kong', 'China')

In [112]:
country_conflicto = conflict_df['country'].unique()

In [113]:
for x in country_conflicto:
    year = conflict_df[conflict_df['country'] == x]['year']
    for i in year:
        df_final.loc[(df_final['country'] == x) & (df_final['year'] == i), 'conflict'] = True

In [114]:
df_final.loc[(df_final['country'] == 'Bolivia') & (df_final['year'] == 1946), :]

,year,country,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,amount,conflict
0,1946,Bolivia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True

In [116]:
df_final['conflict'].fillna(False, inplace=True)

In [120]:
country_df_final = df_final['country'].unique()

In [122]:
df_final['year'].describe()

count   8532.00
mean    1989.00
std       19.97
min     1940.00
25%     1973.00
50%     1992.00
75%     2007.00
max     2018.00
Name: year, dtype: float64

In [124]:
df_final['conflict-1-to-3'] = np.nan
df_final['conflict-4-to-6'] = np.nan
df_final['conflict-7-to-9'] = np.nan
df_final['Prom USA'] = np.nan

In [125]:
for c in country_df_final:
    for x in range(1940, 2019):  


            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-4)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-5)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-6)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-7)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-8)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-9)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            #try:
                #    if(df_final[(df_final['country'] == c) & (df_final['year'] == x-10)]['conflict'].item()):
                #        df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            #except:
                #    pass

In [132]:
for c in country_df_final:
    for x in range(1940, 2018):
        
        yearw_3 = 0
        yearw_2 = 0
        yearw_1 = 0
        prom_w = 0

        yearv_3 = 0
        yearv_2 = 0
        yearv_1 = 0
        prom_v = 0

        yeart_3 = 0
        yeart_2 = 0
        yeart_1 = 0
        prom_t = 0

        yearp_3 = 0
        yearp_2 = 0
        yearp_1 = 0
        prom_p = 0

        # weapons
        try:
            yearw_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Weapons'].item()
        except:
            yearw_3 = 0
        try:
            yearw_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Weapons'].item()
        except:
            yearw_2 = 0
        try:
            yearw_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Weapons'].item()
        except:
            yearw_1 = 0

        prom_w = (yearw_3 + yearw_2 + yearw_1) / 3

        # Vehicles
        try:
            yearv_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Vehicles'].item()
        except:
            yearv_3 = 0

        try:
            yearv_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Vehicles'].item()
        except:
            yearv_2 = 0

        try:
            yearv_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Vehicles'].item()
        except:
            yearv_1 = 0

        prom_v = (yearv_3 + yearv_2 + yearv_1) / 3

        # Tools
        try:
            yeart_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Tools'].item()
        except:
            yeart_3 = 0

        try:
            yeart_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Tools'].item()
        except:
            yeart_2 = 0

        try:
            yeart_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Tools'].item()
        except:
            yeart_1 = 0


        prom_t = (yeart_3 + yeart_2 + yeart_1) / 3
        
        # PROM USA
        try:
            yearp_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].item()
        except:
            yearp_3 = 0

        try:
            yearp_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].item()
        except:
            yearp_2 = 0

        try:
            yearp_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].item()
        except:
            yearp_1 = 0

        prom_p = (yearp_3 + yearp_2 + yearp_1) / 3
            
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Tools'] = prom_t
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Vehicles'] = prom_v
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Weapons'] = prom_w
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom USA'] = prom_p

In [134]:
for x in range(1940, 2019):
    for c in df_final['country'].unique():
        
        yearp_3 = 0
        yearp_2 = 0
        yearp_1 = 0
        prom_p = 0
            
        
            # PROM USA
        try:
            if(df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].isnull().item()):
                yearp_3 = 0
            else:    
                yearp_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].item()
        except:
            yearp_3 = 0

        try:
            if(df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].isnull().item()):
                yearp_2 = 0
            else:
                yearp_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].item()
        except:
            yearp_2 = 0

        try:
            if(df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].isnull().item()):
                yearp_1 = 0
            else:
                yearp_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].item()
        except:
            yearp_1 = 0

        prom_p = (yearp_3 + yearp_2 + yearp_1) / 3
        
        
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom USA'] = prom_p
        #print("Year: {}, yearp_3: {}, yearp_2: {}, yearp_1: {}, prom_p: {}".format(x, yearp_3, yearp_2, yearp_1, prom_p))

In [135]:
x = 2018
for c in df_final['country'].unique():
        
        yearw_3 = 0
        yearw_2 = 0
        yearw_1 = 0
        prom_w = 0

        yearv_3 = 0
        yearv_2 = 0
        yearv_1 = 0
        prom_v = 0

        yeart_3 = 0
        yeart_2 = 0
        yeart_1 = 0
        prom_t = 0


        # weapons
        try:
            yearw_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Weapons'].item()
        except:
            yearw_3 = 0
        try:
            yearw_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Weapons'].item()
        except:
            yearw_2 = 0
        try:
            yearw_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Weapons'].item()
        except:
            yearw_1 = 0

        prom_w = (yearw_3 + yearw_2 + yearw_1) / 3

        # Vehicles
        try:
            yearv_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Vehicles'].item()
        except:
            yearv_3 = 0

        try:
            yearv_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Vehicles'].item()
        except:
            yearv_2 = 0

        try:
            yearv_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Vehicles'].item()
        except:
            yearv_1 = 0

        prom_v = (yearv_3 + yearv_2 + yearv_1) / 3

        # Tools
        try:
            yeart_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Tools'].item()
        except:
            yeart_3 = 0

        try:
            yeart_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Tools'].item()
        except:
            yeart_2 = 0

        try:
            yeart_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Tools'].item()
        except:
            yeart_1 = 0


        prom_t = (yeart_3 + yeart_2 + yeart_1) / 3
            
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Tools'] = prom_t
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Vehicles'] = prom_v
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Weapons'] = prom_w

In [136]:
df_final.drop(list(df_final.loc[(df_final['Tools'] == 0) & (df_final['Vehicles'] == 0) & (df_final['Weapons'] == 0) & (df_final['Prom Tools'] == 0) & (df_final['Prom Vehicles'] == 0) & (df_final['Prom Weapons'] == 0) & (df_final['conflict'] == False) & (df_final['conflict-1-to-3'] == False) & (df_final['conflict-4-to-6'] == False) & (df_final['conflict-7-to-9'] == False), :].index), inplace=True)

In [137]:
df_final.head()

,year,country,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,amount,conflict,conflict-1-to-3,conflict-4-to-6,conflict-7-to-9,Prom USA
0,1946,Bolivia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,NaN,NaN,NaN,0.00
1,1952,Bolivia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,NaN,True,NaN,0.00
2,1967,Bolivia,0.00,53.00,24.00,0.00,9.33,0.00,0.00,True,NaN,NaN,NaN,0.00
3,1946,Cambodia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,NaN,NaN,NaN,0.00
4,1947,Cambodia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,True,NaN,NaN,0.00

In [145]:
label = LabelEncoder()
df_final['country encoded'] = label.fit_transform(df_final['country'])
df_final['conflict'] = label.fit_transform(df_final['conflict'])
df_final['conflict-1-to-3'] = label.fit_transform(df_final['conflict-1-to-3'])
df_final['conflict-4-to-6'] = label.fit_transform(df_final['conflict-4-to-6'])
df_final['conflict-7-to-9'] = label.fit_transform(df_final['conflict-7-to-9'])

In [146]:
for x in df_final:
    df_final[x].fillna(0, inplace=True)

In [148]:
df_final.to_csv('df_final.csv')