In [70]:
import sys
sys.path.insert(0, 'C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts')
from Libs import *
from sklearn import preprocessing

#########

# Intersection_DF no devuelvo nada.. No se si sirve esto.

In [71]:
conflict_df = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/ConflictDB/df_conflicto.csv', index_col=0)

programs_df = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/ForeignAssProgDB/df_total.csv', index_col=0)

trade_df =  pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataCleaning/TradeDB/TradeClean.csv', index_col=0)

conflict_df.rename(columns= {'location':'country'}, inplace=True)
trade_df.rename(columns= {'Recipient':'country', 'Year Weapon of order': 'year'}, inplace=True)
conflict_df.drop_duplicates(inplace=True)

In [72]:
print(conflict_df.columns)
print(trade_df.columns)
print(programs_df.columns)

Index(['year', 'country'], dtype='object')
Index(['country', 'year', 'Tools', 'Vehicles', 'Weapons', 'Prom Tools',
       'Prom Vehicles', 'Prom Weapons'],
      dtype='object')
Index(['country', 'year', 'amount'], dtype='object')

In [73]:
#df_part1 = pd.merge(conflict_df, programs_df, on=['country', 'year'], how='outer', left_index=False, right_index=False)
#df_part2 = pd.merge(df_part1, trade_df, on=['country', 'year'], how='outer', left_index=False, right_index=False)

df_final = pd.merge(trade_df, programs_df, conflict_df, on=['country', 'year'], how='outer', left_index=False, right_index=False)
#df_final = pd.merge(df_final, conflict_df, on=['country', 'year'], how='outer', left_index=False, right_index=False)
df_final = df_final.drop_duplicates()
df_final['conflict'] = np.nan

TypeError: merge() got multiple values for argument 'how'

In [6]:
df_final.drop(df_final[df_final['country'] == 'Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Africa and Europe Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'African Union'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Arabian Peninsula Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Asia and Near East Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'CENTCOM Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Caribbean Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central African Republic'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central America Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Central and Eastern Europe Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'EUCOM Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'East Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'East Asia and Pacific Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'East and Southern Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Eastern Caribbean Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Eurasia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Europe Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Europe and Eurasia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'FYR'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Global'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Great Lakes Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Lake Chad Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Latin America Region'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Levant Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Latin America Region'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Middle East and North Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Palestinian Territories'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Panama Canal Area Military School'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'South Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'South Caucasus Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'South and Central Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southeast Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southern Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southern Cone Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Southwest Asia Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Sub-Saharan Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'UAE'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'UN Transitional Administration in East Timor'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Unknown recipient(s)'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'West Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'West and North Africa Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Western Hemisphere Regional'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'Western Sahara'].index.tolist(), inplace=True)
df_final.drop(df_final[df_final['country'] == 'West and North Africa Regional'].index.tolist(), inplace=True)

In [7]:
df_final['country'] = df_final['country'].str.strip().str.replace('United States of America', 'United States').str.replace('Zimbabwe \(Rhodesia\)', 'Zimbabwe').str.replace('Yemen \(North Yemen\)', 'Yemen').str.replace('Viet Nam', 'Vietnam').str.replace('Vietnam \(North Vietnam\)', 'Vietnam').str.replace('The Gambia', 'Gambia').str.replace('Soviet Union', 'Russia').str.replace('South Vietnam', 'Vietnam').str.replace('South Yemen', 'Yemen').str.replace('South Sudan', 'Sudan').str.replace('St. Vincent and the Grenadines', 'Saint Vincent').str.replace('St. Kitts and Nevis', 'Saint Kitts and Nevis').str.replace('Rumania', 'Romania').str.replace('Northern Cyprus', 'Cyprus').str.replace('North Yemen', 'Yemen').str.replace('Madagascar \(Malagasy\)', 'Madagascar').str.replace('Macedonia \(FYROM\)', 'Macedonia').str.replace('Libya GNC', 'Libya').str.replace('Libya HoR', 'Libya').str.replace('Ivory Coast', "Cote d'Ivoire").str.replace('Germany \(FRG\)', 'Germany').str.replace('East Germany \(GDR\)', 'Germany').str.replace('DR Congo \(Zaire\)', 'Congo').str.replace('DR Congo', 'Congo').str.replace('Bosnia-Herzegovina', 'Bosnia and Herzegovina').str.replace('Yemen \(Yemen\)', 'Yemen').str.replace('Congo \(Zaire\)', 'Congo').str.replace('Hong Kong', 'China')

In [9]:
df_final.fillna(0, inplace=True)

In [61]:
df_final = df_final.merge(conflict_df, on=['country', 'year'])

In [62]:
country_conflicto = conflict_df['country'].unique()

In [63]:
for x in country_conflicto:
    year = conflict_df[conflict_df['country'] == x]['year']
    for i in year:
        df_final.loc[(df_final['country'] == x) & (df_final['year'] == i), 'conflict'] = True

In [64]:
df_final.loc[(df_final['country'] == 'Bolivia') & (df_final['year'] == 1946), :]

Empty DataFrame
Columns: [country, year, Tools, Vehicles, Weapons, Prom Tools, Prom Vehicles, Prom Weapons, amount, conflict]
Index: []

In [55]:
df_final[df_final['country'] == 'Bolivia']

,country,year,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,amount,conflict
116,Bolivia,1967,0.00,53.00,24.00,0.00,0.00,0.00,0.00,True

In [37]:
df_final['Tools'].fillna(0, inplace=True)
df_final['Vehicles'].fillna(0, inplace=True)
df_final['Weapons'].fillna(0, inplace=True)

In [38]:
country_df_final = df_final['country'].unique()

In [39]:
df_final['conflict-1-to-3'] = np.nan
df_final['conflict-4-to-6'] = np.nan
df_final['conflict-7-to-9'] = np.nan
df_final['Prom USA'] = np.nan

In [40]:
for c in country_df_final:
    for x in range(1940, 2018):
        
        yearw_3 = 0
        yearw_2 = 0
        yearw_1 = 0
        prom_w = 0

        yearv_3 = 0
        yearv_2 = 0
        yearv_1 = 0
        prom_v = 0

        yeart_3 = 0
        yeart_2 = 0
        yeart_1 = 0
        prom_t = 0

        yearp_3 = 0
        yearp_2 = 0
        yearp_1 = 0
        prom_p = 0

        # weapons
        try:
            yearw_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Weapons'].item()
        except:
            yearw_3 = 0
        try:
            yearw_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Weapons'].item()
        except:
            yearw_2 = 0
        try:
            yearw_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Weapons'].item()
        except:
            yearw_1 = 0

        prom_w = (yearw_3 + yearw_2 + yearw_1) / 3

        # Vehicles
        try:
            yearv_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Vehicles'].item()
        except:
            yearv_3 = 0

        try:
            yearv_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Vehicles'].item()
        except:
            yearv_2 = 0

        try:
            yearv_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Vehicles'].item()
        except:
            yearv_1 = 0

        prom_v = (yearv_3 + yearv_2 + yearv_1) / 3

        # Tools
        try:
            yeart_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Tools'].item()
        except:
            yeart_3 = 0

        try:
            yeart_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Tools'].item()
        except:
            yeart_2 = 0

        try:
            yeart_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Tools'].item()
        except:
            yeart_1 = 0


        prom_t = (yeart_3 + yeart_2 + yeart_1) / 3
        
        # PROM USA
        try:
            yearp_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].item()
        except:
            yearp_3 = 0

        try:
            yearp_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].item()
        except:
            yearp_2 = 0

        try:
            yearp_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].item()
        except:
            yearp_1 = 0

        prom_p = (yearp_3 + yearp_2 + yearp_1) / 3
            
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Tools'] = prom_t
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Vehicles'] = prom_v
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Weapons'] = prom_w
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom USA'] = prom_p

In [41]:
for c in country_df_final:
    for x in range(1940, 2019):  


            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-1-to-3'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-5'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-4)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-5)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
                    #df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            except:
                pass

            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-6)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-4-to-6'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-7)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-8)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            try:
                if(df_final[(df_final['country'] == c) & (df_final['year'] == x-9)]['conflict'].item()):
                    df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-7-to-9'] = True
            except:
                pass
            #try:
                #    if(df_final[(df_final['country'] == c) & (df_final['year'] == x-10)]['conflict'].item()):
                #        df_final.loc[(df_final['country'] == c) & (df_final['year'] == x), 'conflict-10'] = True
            #except:
                #    pass

In [42]:
for x in range(1940, 2019):
    for c in df_final['country'].unique():
        
        yearp_3 = 0
        yearp_2 = 0
        yearp_1 = 0
        prom_p = 0
            
        
            # PROM USA
        try:
            if(df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].isnull().item()):
                yearp_3 = 0
            else:    
                yearp_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['amount'].item()
        except:
            yearp_3 = 0

        try:
            if(df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].isnull().item()):
                yearp_2 = 0
            else:
                yearp_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['amount'].item()
        except:
            yearp_2 = 0

        try:
            if(df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].isnull().item()):
                yearp_1 = 0
            else:
                yearp_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['amount'].item()
        except:
            yearp_1 = 0

        prom_p = (yearp_3 + yearp_2 + yearp_1) / 3
        
        
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom USA'] = prom_p
        #print("Year: {}, yearp_3: {}, yearp_2: {}, yearp_1: {}, prom_p: {}".format(x, yearp_3, yearp_2, yearp_1, prom_p))

In [44]:
x = 2018
for c in df_final['country'].unique():
        
        yearw_3 = 0
        yearw_2 = 0
        yearw_1 = 0
        prom_w = 0

        yearv_3 = 0
        yearv_2 = 0
        yearv_1 = 0
        prom_v = 0

        yeart_3 = 0
        yeart_2 = 0
        yeart_1 = 0
        prom_t = 0


        # weapons
        try:
            yearw_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Weapons'].item()
        except:
            yearw_3 = 0
        try:
            yearw_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Weapons'].item()
        except:
            yearw_2 = 0
        try:
            yearw_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Weapons'].item()
        except:
            yearw_1 = 0

        prom_w = (yearw_3 + yearw_2 + yearw_1) / 3

        # Vehicles
        try:
            yearv_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Vehicles'].item()
        except:
            yearv_3 = 0

        try:
            yearv_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Vehicles'].item()
        except:
            yearv_2 = 0

        try:
            yearv_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Vehicles'].item()
        except:
            yearv_1 = 0

        prom_v = (yearv_3 + yearv_2 + yearv_1) / 3

        # Tools
        try:
            yeart_3 = df_final[(df_final['country'] == c) & (df_final['year'] == x-3)]['Tools'].item()
        except:
            yeart_3 = 0

        try:
            yeart_2 = df_final[(df_final['country'] == c) & (df_final['year'] == x-2)]['Tools'].item()
        except:
            yeart_2 = 0

        try:
            yeart_1 = df_final[(df_final['country'] == c) & (df_final['year'] == x-1)]['Tools'].item()
        except:
            yeart_1 = 0


        prom_t = (yeart_3 + yeart_2 + yeart_1) / 3
            
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Tools'] = prom_t
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Vehicles'] = prom_v
        df_final.loc[(df_final['year'] == x) & (df_final['country'] == c), 'Prom Weapons'] = prom_w

In [45]:
df_final.drop(list(df_final.loc[(df_final['Tools'] == 0) & (df_final['Vehicles'] == 0) & (df_final['Weapons'] == 0) & (df_final['Prom Tools'] == 0) & (df_final['Prom Vehicles'] == 0) & (df_final['Prom Weapons'] == 0) & (df_final['conflict'] == False) & (df_final['conflict-1-to-3'] == False) & (df_final['conflict-4-to-6'] == False) & (df_final['conflict-7-to-9'] == False), :].index), inplace=True)

In [46]:
df_final.head()

,country,year,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,amount,conflict,conflict-1-to-3,conflict-4-to-6,conflict-7-to-9,Prom USA
0,Afghanistan,1955,0.00,184.00,0.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00
1,Afghanistan,1956,0.00,32.00,0.00,0.00,61.33,0.00,nan,NaN,True,NaN,NaN,0.00
2,Afghanistan,1958,0.00,50.00,450.00,0.00,72.00,0.00,nan,NaN,True,NaN,NaN,0.00
3,Afghanistan,1960,0.00,74.00,200.00,0.00,16.67,150.00,nan,NaN,True,True,NaN,0.00
4,Afghanistan,1961,0.00,100.00,250.00,0.00,41.33,216.67,nan,NaN,True,True,NaN,0.00

In [47]:
encoder = preprocessing.LabelEncoder()
encoder.fit(df_final['country'].unique())

LabelEncoder()

In [48]:
countries_total = df_final['country']
countries_total_encoded = encoder.transform(countries_total)

In [49]:
len(countries_total_encoded)

8084

In [50]:
df_final['country encoded'] = countries_total_encoded

In [51]:
df_final

,country,year,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,amount,conflict,conflict-1-to-3,conflict-4-to-6,conflict-7-to-9,Prom USA,country encoded
0,Afghanistan,1955,0.00,184.00,0.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,0
1,Afghanistan,1956,0.00,32.00,0.00,0.00,61.33,0.00,nan,NaN,True,NaN,NaN,0.00,0
2,Afghanistan,1958,0.00,50.00,450.00,0.00,72.00,0.00,nan,NaN,True,NaN,NaN,0.00,0
3,Afghanistan,1960,0.00,74.00,200.00,0.00,16.67,150.00,nan,NaN,True,True,NaN,0.00,0
4,Afghanistan,1961,0.00,100.00,250.00,0.00,41.33,216.67,nan,NaN,True,True,NaN,0.00,0
5,Afghanistan,1963,0.00,36.00,100.00,0.00,58.00,150.00,nan,NaN,True,True,True,0.00,0
6,Afghanistan,1964,18.00,0.00,0.00,0.00,45.33,116.67,nan,NaN,True,True,True,0.00,0
7,Afghanistan,1965,2.00,50.00,406.00,6.00,12.00,33.33,nan,NaN,True,True,True,0.00,0
8,Afghanistan,1967,0.00,1.00,0.00,6.67,16.67,135.33,nan,NaN,True,True,True,0.00,0
9,Afghanistan,1969,0.00,1.00,0.00,0.00,0.33,0.00,nan,NaN,True,True,True,0.00,0
10,Afghanistan,1970,0.00,92.00,250.00,0.00,0.67,0.00,nan,NaN,True,True,True,0.00,0
11,Afghanistan,1973,0.00,100.00,0.00,0.00,30.67,83.33,nan,NaN,True,True,True,0.00,0
12,Afghanistan,1974,0.00,20.00,0.00,0.00,33.33,0.00,nan,NaN,True,True,True,0.00,0
13,Afghanistan,1976,0.00,36.00,0.00,0.00,40.00,0.00,nan,NaN,True,True,True,0.00,0
14,Afghanistan,1977,26.00,26.00,0.00,0.00,18.67,0.00,nan,NaN,True,True,True,0.00,0
15,Afghanistan,1978,0.00,896.00,1458.00,8.67,20.67,0.00,nan,True,True,True,True,0.00,0
16,Afghanistan,1979,0.00,792.00,7408.00,8.67,319.33,486.00,nan,True,True,True,True,0.00,0
17,Afghanistan,1980,0.00,90.00,1000.00,8.67,571.33,2955.33,nan,True,True,True,True,0.00,0
18,Afghanistan,1981,0.00,50.00,0.00,0.00,592.67,3288.67,nan,True,True,True,True,0.00,0
19,Afghanistan,1982,0.00,0.00,8.00,0.00,310.67,2802.67,nan,True,True,True,True,0.00,0
20,Afghanistan,1984,1.00,61.00,0.00,0.00,16.67,2.67,nan,True,True,True,True,0.00,0
21,Afghanistan,1985,0.00,36.00,125.00,0.33,20.33,2.67,nan,True,True,True,True,0.00,0
22,Afghanistan,1986,0.00,89.00,400.00,0.33,32.33,41.67,nan,True,True,True,True,0.00,0
23,Afghanistan,1987,0.00,193.00,1722.00,0.33,62.00,175.00,nan,True,True,True,True,0.00,0
24,Afghanistan,1988,0.00,2396.00,1075.00,0.00,106.00,749.00,nan,True,True,True,True,0.00,0
25,Afghanistan,1989,0.00,52.00,0.00,0.00,892.67,1065.67,nan,True,True,True,True,0.00,0
26,Afghanistan,2002,0.00,9.00,0.00,0.00,0.00,0.00,187846000.00,True,True,NaN,NaN,16628850.00,0
27,Afghanistan,2004,6.00,4.00,188.00,0.00,3.00,0.00,1119611734.00,True,True,True,NaN,233203210.67,0
28,Afghanistan,2006,0.00,800.00,24.00,2.00,1.33,62.67,2207266814.00,True,True,True,NaN,1448110865.67,0
29,Afghanistan,2007,0.00,25.00,24.00,2.00,268.00,70.67,8591783138.00,True,True,True,True,2027584188.00,0
30,Afghanistan,2008,0.00,4751.00,159.00,0.00,275.00,16.00,3789982423.00,True,True,True,True,4518307989.33,0
31,Afghanistan,2009,0.00,6.00,60.00,0.00,1858.67,69.00,6292686219.00,True,True,True,True,4863010791.67,0
32,Afghanistan,2010,0.00,6821.00,0.00,0.00,1594.00,81.00,10024552841.00,True,True,True,True,6224817260.00,0
33,Afghanistan,2011,0.00,803.00,281.00,0.00,3859.33,73.00,11411254431.00,True,True,True,True,6702407161.00,0
34,Afghanistan,2012,0.00,25.00,227.00,0.00,2543.33,113.67,9937131505.00,True,True,True,True,9242831163.67,0
35,Afghanistan,2013,20.00,62.00,135.00,0.00,2549.67,169.33,5889440449.00,True,True,True,True,10457646259.00,0
36,Afghanistan,2014,0.00,12.00,222.00,6.67,296.67,214.33,4572803062.00,True,True,True,True,9079275461.67,0
37,Afghanistan,2015,0.00,81.00,55.00,6.67,33.00,194.67,4511934505.00,True,True,True,True,6799791672.00,0
38,Afghanistan,2016,0.00,2159.00,0.00,6.67,51.67,137.33,4200770600.00,True,True,True,True,4991392672.00,0
39,Afghanistan,2017,6.00,269.00,55.00,0.00,750.67,92.33,4486515000.00,NaN,True,True,True,4428502722.33,0
40,Albania,1949,0.00,5.00,0.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,1
41,Albania,1951,0.00,21.00,0.00,0.00,1.67,0.00,nan,NaN,True,NaN,NaN,0.00,1
42,Albania,1952,0.00,0.00,775.00,0.00,8.67,0.00,nan,NaN,True,NaN,NaN,0.00,1
43,Albania,1953,0.00,12.00,0.00,0.00,7.00,258.33,nan,NaN,True,True,NaN,0.00,1
44,Albania,1954,0.00,28.00,0.00,0.00,11.00,258.33,nan,NaN,True,True,NaN,0.00,1
45,Albania,1955,28.00,152.00,56.00,0.00,13.33,258.33,nan,NaN,True,True,NaN,0.00,1
46,Albania,1956,0.00,9.00,300.00,9.33,64.00,18.67,nan,NaN,True,True,True,0.00,1
47,Albania,1957,6.00,7.00,0.00,9.33,63.00,118.67,nan,NaN,True,True,True,0.00,1
48,Albania,1958,0.00,8.00,0.00,11.33,56.00,118.67,nan,NaN,True,True,True,0.00,1
49,Albania,1959,0.00,45.00,0.00,2.00,8.00,100.00,nan,NaN,True,True,True,0.00,1
50,Albania,1960,2.00,0.00,0.00,2.00,20.00,0.00,nan,NaN,True,True,True,0.00,1
51,Albania,1961,0.00,11.00,0.00,0.67,17.67,0.00,nan,NaN,True,True,True,0.00,1
52,Albania,1962,0.00,103.00,0.00,0.67,18.67,0.00,nan,NaN,True,True,True,0.00,1
53,Albania,1963,0.00,16.00,0.00,0.67,38.00,0.00,nan,NaN,True,True,True,0.00,1
54,Albania,1964,0.00,17.00,400.00,0.00,43.33,0.00,nan,NaN,True,True,True,0.00,1
55,Albania,1965,0.00,721.00,450.00,0.00,45.33,133.33,nan,NaN,True,True,True,0.00,1
56,Albania,1966,0.00,37.00,0.00,0.00,251.33,283.33,nan,NaN,True,True,True,0.00,1
57,Albania,1967,0.00,32.00,0.00,0.00,258.33,283.33,nan,NaN,True,True,True,0.00,1
58,Albania,1968,0.00,0.00,360.00,0.00,263.33,150.00,nan,NaN,True,True,True,0.00,1
59,Albania,1969,0.00,12.00,0.00,0.00,23.00,120.00,nan,NaN,True,True,True,0.00,1
60,Albania,1970,0.00,35.00,152.00,0.00,14.67,120.00,nan,NaN,True,True,True,0.00,1
61,Albania,1971,0.00,1.00,0.00,0.00,15.67,170.67,nan,NaN,True,True,True,0.00,1
62,Albania,1972,0.00,0.00,103.00,0.00,16.00,50.67,nan,NaN,True,True,True,0.00,1
63,Albania,1974,0.00,6.00,0.00,0.00,0.33,34.33,nan,NaN,True,True,True,0.00,1
64,Albania,1975,0.00,0.00,50.00,0.00,2.00,34.33,nan,NaN,True,True,True,0.00,1
65,Albania,1994,0.00,0.00,16.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,1
66,Albania,2003,0.00,14.00,0.00,0.00,0.00,0.00,11494892.00,NaN,True,True,True,6564637.00,1
67,Albania,2006,0.00,6.00,0.00,0.00,4.67,0.00,10119106.00,NaN,True,True,True,14059325.33,1
68,Albania,2009,0.00,4.00,0.00,0.00,2.00,0.00,6940109.00,NaN,True,True,True,13801557.67,1
69,Albania,2014,0.00,2.00,0.00,0.00,0.00,0.00,10653137.00,NaN,True,True,True,9672554.00,1
70,Albania,2016,0.00,0.00,3.00,0.00,0.67,0.00,7482700.00,NaN,True,True,True,10093375.00,1
71,Algeria,1961,0.00,45.00,100.00,0.00,0.00,0.00,nan,True,NaN,NaN,NaN,0.00,2
72,Algeria,1962,2.00,153.00,120.00,0.00,15.00,33.33,nan,True,True,NaN,NaN,0.00,2
73,Algeria,1963,0.00,162.00,400.00,0.67,66.00,73.33,nan,True,True,NaN,NaN,0.00,2
74,Algeria,1964,0.00,88.00,0.00,0.67,120.00,206.67,nan,NaN,True,NaN,NaN,0.00,2
75,Algeria,1965,34.00,198.00,540.00,0.67,134.33,173.33,nan,NaN,True,True,NaN,0.00,2
76,Algeria,1966,0.00,206.00,50.00,11.33,149.33,313.33,nan,NaN,True,True,NaN,0.00,2
77,Algeria,1967,0.00,9.00,0.00,11.33,164.00,196.67,nan,NaN,True,True,NaN,0.00,2
78,Algeria,1968,2.00,4.00,0.00,11.33,137.67,196.67,nan,NaN,True,True,True,0.00,2
79,Algeria,1969,0.00,31.00,0.00,0.67,73.00,16.67,nan,NaN,True,True,True,0.00,2
80,Algeria,1971,0.00,0.00,200.00,0.67,11.67,0.00,nan,NaN,True,True,True,0.00,2
81,Algeria,1972,0.00,34.00,1000.00,0.00,10.33,66.67,nan,NaN,True,True,True,0.00,2
82,Algeria,1973,0.00,0.00,9000.00,0.00,11.33,400.00,nan,NaN,True,True,True,0.00,2
83,Algeria,1974,12.00,86.00,0.00,0.00,11.33,3400.00,nan,NaN,True,True,True,0.00,2
84,Algeria,1975,0.00,27.00,75.00,4.00,40.00,3333.33,nan,NaN,True,True,True,0.00,2
85,Algeria,1976,10.00,153.00,1300.00,4.00,37.67,3025.00,nan,NaN,True,True,True,0.00,2
86,Algeria,1977,3.00,447.00,715.00,7.33,88.67,458.33,nan,NaN,True,True,True,0.00,2
87,Algeria,1978,18.00,1103.00,1452.00,4.33,209.00,696.67,nan,NaN,True,True,True,0.00,2
88,Algeria,1979,0.00,203.00,125.00,10.33,567.67,1155.67,nan,NaN,True,True,True,0.00,2
89,Algeria,1980,0.00,53.00,600.00,7.00,584.33,764.00,nan,NaN,True,True,True,0.00,2
90,Algeria,1981,0.00,72.00,182.00,6.00,453.00,725.67,nan,NaN,True,True,True,0.00,2
91,Algeria,1982,8.00,3.00,905.00,0.00,109.33,302.33,nan,NaN,True,True,True,0.00,2
92,Algeria,1983,12.00,11.00,66.00,2.67,42.67,562.33,nan,NaN,True,True,True,0.00,2
93,Algeria,1984,0.00,2.00,0.00,6.67,28.67,384.33,nan,NaN,True,True,True,0.00,2
94,Algeria,1985,0.00,42.00,40.00,6.67,5.33,323.67,nan,NaN,True,True,True,0.00,2
95,Algeria,1986,0.00,49.00,79.00,4.00,18.33,35.33,nan,NaN,True,True,True,0.00,2
96,Algeria,1987,32.00,32.00,0.00,0.00,31.00,39.67,nan,NaN,True,True,True,0.00,2
97,Algeria,1988,0.00,51.00,0.00,10.67,41.00,39.67,nan,NaN,True,True,True,0.00,2
98,Algeria,1989,0.00,233.00,2355.00,10.67,44.00,26.33,nan,NaN,True,True,True,0.00,2
99,Algeria,1990,0.00,216.00,0.00,10.67,105.33,785.00,nan,NaN,True,True,True,0.00,2
100,Algeria,1991,0.00,5.00,0.00,0.00,166.67,785.00,nan,True,True,True,True,0.00,2
101,Algeria,1992,200.00,0.00,202.00,0.00,151.33,785.00,nan,True,True,True,True,0.00,2
102,Algeria,1993,0.00,0.00,151.00,66.67,73.67,67.33,nan,True,True,True,True,0.00,2
103,Algeria,1994,0.00,118.00,2190.00,66.67,1.67,117.67,nan,True,True,True,True,0.00,2
104,Algeria,1995,7.00,7.00,3.00,66.67,39.33,847.67,nan,True,True,True,True,0.00,2
105,Algeria,1996,0.00,10.00,0.00,2.33,41.67,781.33,nan,True,True,True,True,0.00,2
106,Algeria,1997,4.00,97.00,24.00,2.33,45.00,731.00,nan,True,True,True,True,0.00,2
107,Algeria,1998,4.00,119.00,1054.00,3.67,38.00,9.00,nan,True,True,True,True,0.00,2
108,Algeria,1999,0.00,9.00,356.00,2.67,75.33,359.33,14422.00,True,True,True,True,0.00,2
109,Algeria,2000,3.00,34.00,0.00,2.67,75.00,478.00,115000.00,True,True,True,True,4807.33,2
110,Algeria,2001,17.00,36.00,0.00,2.33,54.00,470.00,140076.00,True,True,True,True,43140.67,2
111,Algeria,2002,0.00,42.00,0.00,6.67,26.33,118.67,84015.00,True,True,True,True,89832.67,2
112,Algeria,2003,0.00,9.00,132.00,6.67,37.33,0.00,713713.00,True,True,True,True,113030.33,2
113,Algeria,2004,14.00,28.00,2.00,5.67,29.00,44.00,1005749.00,True,True,True,True,312601.33,2
114,Algeria,2005,0.00,0.00,4414.00,4.67,26.33,44.67,1540121.00,True,True,True,True,601159.00,2
115,Algeria,2006,70.00,271.00,2443.00,4.67,12.33,1516.00,1671146.00,True,True,True,True,1086527.67,2
116,Algeria,2007,6.00,31.00,88.00,28.00,99.67,2286.33,3656114.00,True,True,True,True,1405672.00,2
117,Algeria,2008,0.00,0.00,2.00,25.33,100.67,2315.00,1778755.00,True,True,True,True,2289127.00,2
118,Algeria,2009,0.00,23.00,30.00,25.33,100.67,844.33,1741132.00,True,True,True,True,2368671.67,2
119,Algeria,2010,0.00,16.00,0.00,2.00,18.00,40.00,2416929.00,True,True,True,True,2392000.33,2
120,Algeria,2011,3.00,142.00,134.00,0.00,13.00,10.67,2253798.00,True,True,True,True,1978938.67,2
121,Algeria,2012,42.00,284.00,302.00,1.00,60.33,54.67,2813165.00,True,True,True,True,2137286.33,2
122,Algeria,2013,3.00,77.00,1121.00,15.00,147.33,145.33,3365359.00,True,True,True,True,2494630.67,2
123,Algeria,2014,3.00,203.00,5286.00,16.00,167.67,519.00,3259476.00,True,True,True,True,2810774.00,2
124,Algeria,2015,0.00,37.00,0.00,16.00,188.00,2236.33,3361305.00,True,True,True,True,3146000.00,2
125,Algeria,2016,0.00,18.00,0.00,2.00,105.67,2135.67,2883000.00,True,True,True,True,3328713.33,2
126,Angola,1974,0.00,57.00,0.00,0.00,0.00,0.00,nan,True,NaN,NaN,NaN,0.00,3
127,Angola,1975,1.00,481.00,1906.00,0.00,19.00,0.00,nan,True,True,NaN,NaN,0.00,3
128,Angola,1976,0.00,15.00,90.00,0.33,179.33,635.33,nan,True,True,NaN,NaN,0.00,3
129,Angola,1977,0.00,223.00,0.00,0.33,184.33,665.33,nan,True,True,NaN,NaN,0.00,3
130,Angola,1978,0.00,20.00,0.00,0.33,239.67,665.33,nan,True,True,True,NaN,0.00,3
131,Angola,1979,41.00,28.00,400.00,0.00,86.00,30.00,nan,True,True,True,NaN,0.00,3
132,Angola,1980,17.00,419.00,368.00,13.67,90.33,133.33,nan,True,True,True,NaN,0.00,3
133,Angola,1981,12.00,18.00,90.00,19.33,155.67,256.00,nan,True,True,True,True,0.00,3
134,Angola,1982,0.00,77.00,600.00,23.33,155.00,286.00,nan,True,True,True,True,0.00,3
135,Angola,1983,36.00,110.00,1307.00,9.67,171.33,352.67,nan,True,True,True,True,0.00,3
136,Angola,1984,0.00,30.00,750.00,16.00,68.33,665.67,nan,True,True,True,True,0.00,3
137,Angola,1985,7.00,212.00,580.00,12.00,72.33,885.67,nan,True,True,True,True,0.00,3
138,Angola,1986,18.00,81.00,572.00,14.33,117.33,879.00,nan,True,True,True,True,0.00,3
139,Angola,1987,0.00,320.00,1200.00,8.33,107.67,634.00,nan,True,True,True,True,0.00,3
140,Angola,1988,0.00,30.00,0.00,8.33,204.33,784.00,nan,True,True,True,True,0.00,3
141,Angola,1990,6.00,2.00,150.00,0.00,116.67,400.00,nan,True,True,True,True,0.00,3
142,Angola,1991,0.00,4.00,0.00,2.00,10.67,50.00,nan,True,True,True,True,0.00,3
143,Angola,1992,0.00,4.00,0.00,2.00,2.00,50.00,nan,True,True,True,True,0.00,3
144,Angola,1993,0.00,376.00,23.00,2.00,3.33,50.00,nan,True,True,True,True,0.00,3
145,Angola,1994,0.00,52.00,3.00,0.00,128.00,7.67,nan,True,True,True,True,0.00,3
146,Angola,1995,0.00,4.00,0.00,0.00,144.00,8.67,nan,True,True,True,True,0.00,3
147,Angola,1996,0.00,8.00,0.00,0.00,144.00,8.67,nan,True,True,True,True,0.00,3
148,Angola,1997,0.00,67.00,0.00,0.00,21.33,1.00,nan,True,True,True,True,0.00,3
149,Angola,1998,6.00,12.00,52.00,0.00,26.33,0.00,nan,True,True,True,True,0.00,3
150,Angola,1999,0.00,503.00,56.00,2.00,29.00,17.33,nan,True,True,True,True,0.00,3
151,Angola,2000,0.00,36.00,12.00,2.00,194.00,36.00,3110422.00,True,True,True,True,0.00,3
152,Angola,2001,0.00,3.00,0.00,2.00,183.67,40.00,2853667.00,True,True,True,True,1036807.33,3
153,Angola,2002,0.00,14.00,11.00,0.00,180.67,22.67,2936435.00,True,True,True,True,1988029.67,3
154,Angola,2004,0.00,8.00,0.00,0.00,5.67,3.67,5829712.00,True,True,True,True,3322105.00,3
155,Angola,2005,0.00,3.00,0.00,0.00,7.33,3.67,6676026.00,NaN,True,True,True,4314120.00,3
156,Angola,2006,0.00,3.00,0.00,0.00,3.67,0.00,6622746.00,NaN,True,True,True,5560650.33,3
157,Angola,2011,6.00,6.00,0.00,0.00,0.00,0.00,7923608.00,NaN,True,True,True,7549290.67,3
158,Angola,2012,0.00,6.00,0.00,2.00,2.00,0.00,7971949.00,NaN,True,True,True,7561047.33,3
159,Angola,2013,45.00,20.00,45.00,2.00,4.00,0.00,6488613.00,NaN,True,True,True,7958794.33,3
160,Angola,2014,0.00,0.00,71.00,17.00,10.67,15.00,6586636.00,NaN,True,True,True,7461390.00,3
161,Angola,2015,0.00,28.00,27.00,15.00,8.67,38.67,6199335.00,NaN,True,True,True,7015732.67,3
162,Argentina,1946,50.00,0.00,0.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,5
163,Argentina,1948,0.00,15.00,100.00,16.67,0.00,0.00,nan,NaN,True,NaN,NaN,0.00,5
164,Argentina,1950,0.00,20.00,6.00,0.00,5.00,33.33,nan,NaN,True,True,NaN,0.00,5
165,Argentina,1951,0.00,2.00,0.00,0.00,11.67,35.33,nan,NaN,True,True,NaN,0.00,5
166,Argentina,1953,0.00,18.00,0.00,0.00,7.33,2.00,nan,NaN,True,True,True,0.00,5
167,Argentina,1955,0.00,10.00,5.00,0.00,6.00,0.00,nan,True,True,True,True,0.00,5
168,Argentina,1956,0.00,162.00,0.00,0.00,9.33,1.67,nan,NaN,True,True,True,0.00,5
169,Argentina,1957,0.00,53.00,0.00,0.00,57.33,1.67,nan,NaN,True,True,True,0.00,5
170,Argentina,1958,0.00,82.00,0.00,0.00,75.00,1.67,nan,NaN,True,True,True,0.00,5
171,Argentina,1959,0.00,8.00,0.00,0.00,99.00,0.00,nan,NaN,True,True,True,0.00,5
172,Argentina,1960,0.00,122.00,29.00,0.00,47.67,0.00,nan,NaN,True,True,True,0.00,5
173,Argentina,1961,0.00,19.00,0.00,0.00,70.67,9.67,nan,NaN,True,True,True,0.00,5
174,Argentina,1962,0.00,0.00,50.00,0.00,49.67,9.67,nan,NaN,True,True,True,0.00,5
175,Argentina,1963,0.00,6.00,100.00,0.00,47.00,26.33,nan,True,True,True,True,0.00,5
176,Argentina,1964,0.00,3.00,0.00,0.00,8.33,50.00,nan,NaN,True,True,True,0.00,5
177,Argentina,1965,0.00,133.00,175.00,0.00,3.00,50.00,nan,NaN,True,True,True,0.00,5
178,Argentina,1966,66.00,11.00,66.00,0.00,47.33,91.67,nan,NaN,True,True,True,0.00,5
179,Argentina,1967,10.00,89.00,0.00,22.00,49.00,80.33,nan,NaN,True,True,True,0.00,5
180,Argentina,1968,22.00,213.00,460.00,25.33,77.67,80.33,nan,NaN,True,True,True,0.00,5
181,Argentina,1969,0.00,24.00,24.00,32.67,104.33,175.33,nan,NaN,True,True,True,0.00,5
182,Argentina,1970,8.00,72.00,847.00,10.67,108.67,161.33,nan,NaN,True,True,True,0.00,5
183,Argentina,1971,4.00,38.00,192.00,10.00,103.00,443.67,nan,NaN,True,True,True,0.00,5
184,Argentina,1972,216.00,31.00,480.00,4.00,44.67,354.33,nan,NaN,True,True,True,0.00,5
185,Argentina,1973,0.00,4.00,260.00,76.00,47.00,506.33,nan,NaN,True,True,True,0.00,5
186,Argentina,1974,0.00,156.00,0.00,73.33,24.33,310.67,nan,True,True,True,True,0.00,5
187,Argentina,1975,0.00,36.00,636.00,72.00,63.67,246.67,nan,True,True,True,True,0.00,5
188,Argentina,1976,0.00,157.00,0.00,0.00,65.33,298.67,nan,True,True,True,True,0.00,5
189,Argentina,1977,3.00,106.00,295.00,0.00,116.33,212.00,nan,True,True,True,True,0.00,5
190,Argentina,1978,102.00,261.00,112.00,1.00,99.67,310.33,nan,NaN,True,True,True,0.00,5
191,Argentina,1979,55.00,40.00,186.00,35.00,174.67,135.67,nan,NaN,True,True,True,0.00,5
192,Argentina,1980,44.00,73.00,149.00,53.33,135.67,197.67,nan,NaN,True,True,True,0.00,5
193,Argentina,1981,0.00,125.00,339.00,67.00,124.67,149.00,nan,NaN,True,True,True,0.00,5
194,Argentina,1982,2.00,59.00,120.00,33.00,79.33,224.67,nan,True,True,True,True,0.00,5
195,Argentina,1983,0.00,0.00,50.00,15.33,85.67,202.67,nan,NaN,True,True,True,0.00,5
196,Argentina,1985,3.00,30.00,0.00,0.67,19.67,56.67,nan,NaN,True,True,True,0.00,5
197,Argentina,1986,2.00,0.00,40.00,1.00,10.00,16.67,nan,NaN,True,True,True,0.00,5
198,Argentina,1987,30.00,33.00,0.00,1.67,10.00,13.33,nan,NaN,True,True,True,0.00,5
199,Argentina,1988,3.00,0.00,0.00,11.67,21.00,13.33,nan,NaN,True,True,True,0.00,5
200,Argentina,1989,15.00,4.00,30.00,11.67,11.00,13.33,nan,NaN,True,True,True,0.00,5
201,Argentina,1992,10.00,5.00,0.00,5.00,1.33,10.00,nan,NaN,True,True,True,0.00,5
202,Argentina,1993,4.00,34.00,0.00,3.33,1.67,0.00,nan,NaN,True,True,True,0.00,5
203,Argentina,1994,0.00,159.00,12.00,4.67,13.00,0.00,nan,NaN,True,True,True,0.00,5
204,Argentina,1995,8.00,0.00,0.00,4.67,66.00,4.00,nan,NaN,True,True,True,0.00,5
205,Argentina,1996,0.00,24.00,0.00,4.00,64.33,4.00,20042861.00,NaN,True,True,True,0.00,5
206,Argentina,1997,0.00,11.00,9.00,2.67,61.00,4.00,2228908.00,NaN,True,True,True,6680953.67,5
207,Argentina,1998,1.00,3.00,0.00,2.67,11.67,3.00,9990763.00,NaN,True,True,True,7423923.00,5
208,Argentina,1999,0.00,1.00,102.00,0.33,12.67,3.00,4184285.00,NaN,True,True,True,10754177.33,5
209,Argentina,2000,0.00,0.00,42.00,0.33,5.00,37.00,1497256.00,NaN,True,True,True,5467985.33,5
210,Argentina,2001,6.00,3.00,200.00,0.33,1.33,48.00,2371047.00,NaN,True,True,True,5224101.33,5
211,Argentina,2003,2.00,0.00,0.00,2.00,1.00,80.67,3411325.00,NaN,True,True,True,2283488.67,5
212,Argentina,2004,3.00,9.00,0.00,2.67,1.00,66.67,1520558.00,NaN,True,True,True,2921511.67,5
213,Argentina,2006,0.00,20.00,0.00,1.67,3.00,0.00,2013601.00,NaN,True,True,True,2220476.33,5
214,Argentina,2007,9.00,5.00,0.00,1.00,9.67,0.00,3744541.00,NaN,True,True,True,1754568.33,5
215,Argentina,2008,0.00,0.00,4.00,3.00,8.33,0.00,6400872.00,NaN,True,True,True,2495896.00,5
216,Argentina,2009,15.00,5.00,30.00,3.00,8.33,1.33,2956987.00,NaN,True,True,True,4053004.67,5
217,Argentina,2010,0.00,2.00,0.00,8.00,3.33,11.33,2846610.00,NaN,True,True,True,4367466.67,5
218,Argentina,2011,0.00,1.00,0.00,5.00,2.33,11.33,1150750.00,NaN,True,True,True,4068156.33,5
219,Argentina,2012,0.00,10.00,0.00,5.00,2.67,10.00,1157748.00,NaN,True,True,True,2318115.67,5
220,Argentina,2013,1.00,4.00,0.00,0.00,4.33,0.00,777132.00,NaN,True,True,True,1718369.33,5
221,Argentina,2014,5.00,3.00,0.00,0.33,5.00,0.00,672213.00,NaN,True,True,True,1028543.33,5
222,Argentina,2015,0.00,13.00,4.00,2.00,5.67,0.00,660244.00,NaN,True,True,True,869031.00,5
223,Argentina,2016,0.00,30.00,150.00,2.00,6.67,1.33,584000.00,NaN,True,True,True,703196.33,5
224,Argentina,2017,12.00,21.00,0.00,1.67,15.33,51.33,550000.00,NaN,True,True,True,638819.00,5
225,Armenia,1993,0.00,4.00,1343.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,6
226,Armenia,1994,0.00,84.00,0.00,0.00,1.33,447.67,nan,NaN,True,NaN,NaN,0.00,6
227,Armenia,1995,0.00,100.00,272.00,0.00,29.33,447.67,nan,NaN,True,NaN,NaN,0.00,6
228,Armenia,1999,0.00,4.00,0.00,0.00,0.00,0.00,nan,NaN,NaN,True,NaN,0.00,6
229,Armenia,2003,0.00,2.00,0.00,0.00,0.00,0.00,10197635.00,NaN,True,True,True,4896159.00,6

In [54]:
df_final.to_csv('df_final.csv')

In [86]:
df_sinna = pd.read_csv('C:/Users/Franco/Documents/AnacondaProjects/Predicting_Conflicts/DataMerge/df_final.csv', index_col=0)

In [87]:

df_sinna = df_sinna[(df_sinna['Weapons'] != 0) & (df_sinna['Vehicles'] != 0)] 
len(df_sinna)

2686

In [88]:
df_sinna.to_csv('df_final_sinna.csv')

In [89]:
len(df_sinna)

2686

In [90]:
df_sinna.sort_values('Vehicles', ascending=False)

,country,year,Tools,Vehicles,Weapons,Prom Tools,Prom Vehicles,Prom Weapons,amount,conflict,conflict-1-to-3,conflict-4-to-6,conflict-7-to-9,Prom USA,country encoded
2677,Iraq,2005,0.00,9897.00,108.00,14.67,103.00,120.67,5496083893.00,True,True,True,NaN,437201858.00,84
1110,China,1949,0.00,5200.00,3000.00,0.00,0.00,0.00,nan,True,NaN,NaN,NaN,0.00,37
30,Afghanistan,2008,0.00,4751.00,159.00,0.00,275.00,16.00,3789982423.00,True,True,True,True,4518307989.33,0
2666,Iraq,1982,0.00,4550.00,3286.00,31.33,1493.00,2852.33,nan,True,True,True,True,0.00,84
2069,Germany,1957,61.00,4111.00,781.00,0.00,0.67,0.00,nan,NaN,True,True,True,0.00,68
2686,Iraq,2014,0.00,4030.00,8840.00,32.67,49.33,1595.00,386327774.00,True,True,True,True,922059699.00,84
1115,China,1954,28.00,3711.00,25.00,0.00,1164.33,5.33,nan,True,True,True,NaN,0.00,37
2665,Iraq,1981,8.00,3416.00,3882.00,30.33,545.00,1716.67,nan,True,True,True,True,0.00,84
3282,Libya,1976,0.00,2645.00,60.00,201.00,670.67,12436.67,nan,NaN,True,True,True,0.00,103
1401,Czechoslovakia,1950,0.00,2496.00,200.00,0.00,56.67,0.00,nan,NaN,True,NaN,NaN,0.00,49
2068,Germany,1956,396.00,2445.00,8204.00,0.00,14.00,0.00,nan,NaN,True,True,True,0.00,68
24,Afghanistan,1988,0.00,2396.00,1075.00,0.00,106.00,749.00,nan,True,True,True,True,0.00,0
5512,Syria,1977,0.00,2330.00,6100.00,0.00,29.33,698.67,nan,NaN,True,True,True,0.00,180
1421,Czechoslovakia,1973,5.00,2252.00,159.00,33.67,24.00,2793.33,nan,NaN,True,True,True,0.00,49
2070,Germany,1958,2212.00,2201.00,16.00,0.00,0.00,0.00,nan,NaN,NaN,True,True,0.00,68
5513,Syria,1978,0.00,2165.00,2980.00,0.00,799.67,2612.00,nan,NaN,True,True,True,0.00,180
1712,Egypt,1967,10.00,2163.00,2700.00,18.00,108.67,2208.33,nan,True,True,True,True,0.00,55
6355,Yugoslavia,1962,504.00,2121.00,320.00,90.67,52.33,205.00,nan,NaN,True,True,True,0.00,205
6344,Yugoslavia,1951,0.00,2024.00,910.00,0.00,32.33,0.00,nan,NaN,True,NaN,NaN,0.00,205
2067,Germany,1955,64.00,1937.00,343.00,0.00,254.67,52.00,nan,NaN,True,True,NaN,0.00,68
1408,Czechoslovakia,1957,18.00,1812.00,500.00,33.33,117.33,0.00,nan,NaN,True,True,True,0.00,49
2477,India,1985,0.00,1752.00,555.00,63.67,951.00,2587.33,nan,True,True,True,True,0.00,81
1614,Germany,1965,0.00,1745.00,31167.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,68
1412,Czechoslovakia,1963,0.00,1700.00,500.00,0.00,101.33,833.33,nan,NaN,True,True,True,0.00,49
2474,India,1982,14.00,1585.00,3150.00,29.33,408.67,18908.33,nan,True,True,True,True,0.00,81
4803,Saudi Arabia,2015,89.00,1563.00,10095.00,113.00,650.33,8782.67,264867.00,NaN,True,True,True,228948.67,159
1605,Germany,1956,0.00,1524.00,2242.00,0.00,14.00,0.00,nan,NaN,True,True,True,0.00,68
4510,Poland,1963,0.00,1519.00,790.00,0.00,465.67,1096.67,nan,NaN,True,True,True,0.00,148
4515,Poland,1969,0.00,1507.00,31030.00,2.67,356.67,50.00,nan,NaN,True,True,True,0.00,148
5503,Syria,1968,0.00,1501.00,10300.00,6.67,526.33,1480.00,nan,NaN,True,True,True,0.00,180
5187,Russia,1976,0.00,1500.00,6.00,0.00,1.67,0.00,nan,NaN,True,True,NaN,0.00,153
2071,Germany,1959,548.00,1462.00,2121.00,0.00,0.00,0.00,nan,NaN,NaN,True,True,0.00,68
1623,Germany,1974,0.00,1460.00,868.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,68
4054,North Korea,1970,0.00,1450.00,400.00,0.00,149.00,271.67,nan,NaN,True,True,True,0.00,137
4498,Poland,1950,0.00,1395.00,380.00,0.00,104.67,0.00,nan,NaN,True,NaN,NaN,0.00,148
1114,China,1953,0.00,1360.00,16.00,0.00,969.33,200.00,nan,NaN,True,True,NaN,0.00,37
5823,Turkey,1960,0.00,1302.00,212.00,16.00,86.00,177.33,nan,NaN,True,True,True,0.00,190
5508,Syria,1973,12.00,1301.00,5051.00,0.00,451.67,526.67,nan,True,True,True,True,0.00,180
5502,Syria,1967,0.00,1232.00,2540.00,6.67,118.00,633.33,nan,True,True,True,True,0.00,180
4033,North Korea,1949,0.00,1210.00,750.00,0.00,16.67,0.00,nan,True,True,NaN,NaN,0.00,137
5854,Turkey,1991,137.00,1191.00,1536.00,692.67,691.00,1110.00,nan,True,True,True,True,0.00,190
2805,Italy,1955,0.00,1175.00,25.00,45.67,344.67,0.00,nan,NaN,True,True,True,0.00,87
1716,Egypt,1971,11.00,1163.00,256.00,31.33,212.33,4455.00,nan,NaN,True,True,True,0.00,55
5507,Syria,1972,0.00,1148.00,1430.00,6.67,90.67,5050.00,nan,NaN,True,True,True,0.00,180
3281,Libya,1975,60.00,1132.00,938.00,192.67,293.33,12366.67,nan,NaN,True,True,True,0.00,103
2669,Iraq,1985,25.00,1104.00,2485.00,34.33,1709.33,2364.00,nan,True,True,True,True,0.00,84
87,Algeria,1978,18.00,1103.00,1452.00,4.33,209.00,696.67,nan,NaN,True,True,True,0.00,2
2204,Greece,1991,26.00,1078.00,12671.00,17.33,292.67,586.67,nan,NaN,True,True,True,0.00,70
2657,Iraq,1973,0.00,1070.00,21570.00,2.00,103.00,673.00,nan,True,True,True,True,0.00,84
2819,Italy,1970,0.00,1065.00,1000.00,13.33,71.00,447.00,nan,NaN,True,True,True,0.00,87
3285,Libya,1979,5.00,1062.00,1098.00,105.67,1305.67,275.33,nan,NaN,True,True,True,0.00,103
5834,Turkey,1971,5.00,1041.00,760.00,14.33,340.67,204.00,nan,NaN,True,True,True,0.00,190
1869,Ethiopia,1977,20.00,1039.00,4464.00,0.00,7.67,42.67,nan,True,True,True,True,0.00,60
4050,North Korea,1966,0.00,1000.00,550.00,0.00,273.33,2263.33,nan,NaN,True,True,True,0.00,137
5536,Syria,2007,0.00,1000.00,254.00,12.00,2.00,471.67,nan,NaN,True,True,True,0.00,180
2489,India,1998,179.00,987.00,1092.00,61.00,54.33,2372.00,nan,True,True,True,True,0.00,81
4779,Saudi Arabia,1990,1754.00,975.00,5377.00,34.67,151.00,1748.00,nan,NaN,True,True,True,0.00,159
4514,Poland,1968,8.00,963.00,150.00,0.00,95.00,0.00,nan,NaN,True,True,True,0.00,148
2463,India,1971,0.00,939.00,2890.00,8.67,143.00,1085.33,nan,True,True,True,True,0.00,81
4500,Poland,1952,0.00,937.00,4.00,0.00,573.67,393.33,nan,NaN,True,NaN,NaN,0.00,148
2613,Iran,1986,0.00,903.00,7677.00,11.67,38.00,973.00,nan,True,True,True,True,0.00,83
2454,India,1962,20.00,902.00,2012.00,6.00,823.33,166.67,nan,True,True,True,True,0.00,81
759,Bulgaria,1961,0.00,900.00,575.00,31.00,117.67,688.67,nan,NaN,True,True,True,0.00,26
15,Afghanistan,1978,0.00,896.00,1458.00,8.67,20.67,0.00,nan,True,True,True,True,0.00,0
2618,Iran,1991,1.00,862.00,106.00,8.33,163.00,421.67,nan,True,True,True,True,0.00,83
4243,Pakistan,1975,30.00,862.00,56.00,100.00,148.33,491.33,nan,True,True,True,True,0.00,140
2608,Iran,1981,0.00,856.00,2600.00,0.00,46.67,8.33,nan,True,True,True,True,0.00,83
1735,Egypt,1990,7.00,855.00,1118.00,14.33,189.33,1469.00,nan,NaN,True,True,True,0.00,55
4662,Romania,1969,0.00,853.00,5000.00,0.00,66.00,624.00,nan,NaN,True,True,True,0.00,152
1116,China,1955,0.00,845.00,142.00,9.33,1878.00,13.67,nan,NaN,True,True,NaN,0.00,37
1423,Czechoslovakia,1976,0.00,821.00,400.00,2.00,784.00,53.00,nan,NaN,True,True,True,0.00,49
2393,Hungary,1963,6.00,818.00,250.00,0.00,67.33,460.00,nan,NaN,True,True,True,0.00,79
2472,India,1980,69.00,817.00,6000.00,17.33,359.67,16949.33,nan,True,True,True,True,0.00,81
5076,South Korea,1971,0.00,811.00,8.00,0.00,34.00,123.33,nan,NaN,True,True,True,0.00,171
2173,Greece,1960,0.00,808.00,334.00,0.00,244.33,129.67,nan,NaN,True,True,True,0.00,70
2598,Iran,1971,0.00,808.00,7088.00,273.67,255.67,1620.33,nan,NaN,True,True,True,0.00,83
3279,Libya,1973,500.00,805.00,20500.00,61.67,163.00,491.33,nan,NaN,True,True,True,0.00,103
1871,Ethiopia,1980,0.00,804.00,810.00,6.67,374.33,1498.00,nan,True,True,True,True,0.00,60
33,Afghanistan,2011,0.00,803.00,281.00,0.00,3859.33,73.00,11411254431.00,True,True,True,True,6702407161.00,0
3841,Netherlands,1975,0.00,803.00,2282.00,22.67,45.00,2322.67,nan,NaN,True,True,True,0.00,129
28,Afghanistan,2006,0.00,800.00,24.00,2.00,1.33,62.67,2207266814.00,True,True,True,NaN,1448110865.67,0
16,Afghanistan,1979,0.00,792.00,7408.00,8.67,319.33,486.00,nan,True,True,True,True,0.00,0
2507,India,2016,360.00,791.00,395.00,116.00,127.67,8992.67,4167000.00,True,True,True,True,9506947.00,81
6270,Vietnam,1969,0.00,788.00,2738.00,0.00,0.00,0.00,nan,True,NaN,NaN,NaN,0.00,203
6089,United States,1996,792.00,785.00,55.00,0.00,80.00,27.00,nan,NaN,True,True,True,0.00,198
3302,Libya,2012,50.00,780.00,400.00,0.00,21.33,50.00,17119393.00,NaN,True,True,True,520345.67,103
1627,Germany,1978,0.00,778.00,27229.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,68
1111,China,1950,0.00,775.00,600.00,0.00,1733.33,1000.00,nan,True,True,NaN,NaN,0.00,37
3284,Libya,1978,277.00,758.00,626.00,33.33,1430.33,379.33,nan,NaN,True,True,True,0.00,103
4034,North Korea,1950,10.00,748.00,2232.00,0.00,420.00,250.00,nan,True,True,NaN,NaN,0.00,137
6271,Vietnam,1970,0.00,747.00,2925.00,0.00,0.00,0.00,nan,True,NaN,NaN,NaN,0.00,203
2599,Iran,1972,404.00,747.00,3578.00,273.67,344.33,3983.00,nan,NaN,True,True,True,0.00,83
2203,Greece,1990,10.00,745.00,90.00,15.33,44.33,698.00,nan,NaN,True,True,True,0.00,70
2476,India,1984,5.00,743.00,900.00,62.33,707.67,2412.33,nan,True,True,True,True,0.00,81
4800,Saudi Arabia,2012,271.00,743.00,854.00,848.67,264.67,5056.67,160268.00,NaN,True,True,True,515212.00,159
2890,Japan,1955,28.00,733.00,832.00,5.00,511.00,70.33,nan,NaN,True,True,NaN,0.00,89
1602,Germany,1952,0.00,722.00,156.00,2.00,33.00,0.00,nan,NaN,True,NaN,NaN,0.00,68
55,Albania,1965,0.00,721.00,450.00,0.00,45.33,133.33,nan,NaN,True,True,True,0.00,1
4049,North Korea,1965,0.00,720.00,2790.00,1.67,41.67,1337.33,nan,NaN,True,True,True,0.00,137
4097,Yemen,1979,0.00,712.00,2746.00,0.00,0.00,0.00,nan,True,NaN,NaN,True,0.00,204
2469,India,1977,13.00,673.00,230.00,76.00,312.67,1060.33,nan,NaN,True,True,True,0.00,81
5412,Sweden,1994,210.00,671.00,213.00,0.00,9.00,217.00,nan,NaN,True,True,True,0.00,178
5100,South Korea,1995,108.00,663.00,1706.00,38.67,186.00,802.67,nan,NaN,True,True,True,0.00,171
5145,Vietnam,1967,0.00,658.00,700.00,0.00,0.00,0.00,nan,True,NaN,NaN,True,0.00,203
4650,Romania,1955,3.00,658.00,374.00,0.00,244.33,0.00,nan,NaN,True,True,NaN,0.00,152
2664,Iraq,1980,11.00,657.00,2925.00,28.33,344.67,1453.33,nan,True,True,True,True,0.00,84
2072,Germany,1960,0.00,651.00,5550.00,0.00,0.00,0.00,nan,NaN,NaN,True,True,0.00,68
3125,Kuwait,2016,10.00,648.00,218.00,0.67,52.33,168.33,nan,NaN,True,True,True,16772.33,96
4801,Saudi Arabia,2013,2.00,631.00,6535.00,614.00,341.33,4308.67,357714.00,NaN,True,True,True,362952.33,159
5832,Turkey,1969,43.00,623.00,36.00,3.33,151.33,200.00,nan,NaN,True,True,True,0.00,190
2753,Israel,1973,0.00,621.00,5426.00,82.67,158.00,186.00,nan,True,True,True,True,0.00,86
6265,Vietnam,1964,154.00,620.00,5375.00,0.00,0.00,0.00,nan,NaN,NaN,True,True,0.00,203
2670,Iraq,1986,20.00,607.00,3380.00,42.67,560.67,2097.00,nan,True,True,True,True,0.00,84
469,Bangladesh,2017,86.00,607.00,80.00,2.33,10.00,194.00,8760000.00,NaN,True,True,True,36054895.00,12
2077,Germany,1965,270.00,601.00,1731.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,68
5009,South Africa,1961,0.00,600.00,36.00,0.00,30.00,0.00,nan,NaN,True,True,True,0.00,170
748,Bulgaria,1950,0.00,599.00,150.00,0.00,16.67,133.33,nan,NaN,True,NaN,NaN,0.00,26
4258,Pakistan,1990,15.00,599.00,28.00,38.33,62.33,845.67,nan,True,True,True,True,0.00,140
4645,Qatar,2017,1.00,595.00,250.00,158.00,79.00,1240.67,nan,NaN,True,True,True,83686.33,151
4511,Poland,1964,0.00,587.00,850.00,0.00,812.67,776.67,nan,NaN,True,True,True,0.00,148
4802,Saudi Arabia,2014,66.00,577.00,18959.00,510.67,535.33,5460.67,168864.00,NaN,True,True,True,313394.00,159
2662,Iraq,1978,5.00,572.00,475.00,8.33,290.33,3335.00,nan,True,True,True,True,0.00,84
5150,Vietnam,1972,0.00,559.00,385.00,0.00,0.00,0.00,nan,True,NaN,NaN,NaN,0.00,203
2889,Japan,1954,4.00,558.00,191.00,3.67,331.67,6.67,nan,NaN,True,NaN,NaN,0.00,89
2171,Greece,1958,0.00,557.00,85.00,12.00,210.00,78.67,nan,NaN,True,True,True,0.00,70
1739,Egypt,1994,25.00,555.00,201.00,29.67,145.67,586.33,nan,True,True,True,True,0.00,55
1613,Germany,1964,0.00,554.00,300.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,68
1725,Egypt,1980,2.00,552.00,3132.00,13.67,27.00,4191.33,nan,NaN,True,True,True,0.00,55
4667,Romania,1975,0.00,546.00,900.00,0.00,66.67,0.00,nan,NaN,True,True,True,0.00,152
5099,South Korea,1994,10.00,544.00,375.00,39.33,45.67,738.00,nan,NaN,True,True,True,0.00,171
5817,Turkey,1954,0.00,542.00,52.00,0.00,138.67,0.00,nan,NaN,True,True,NaN,0.00,190
1327,Cuba,1960,0.00,541.00,1674.00,0.00,21.33,0.00,nan,NaN,True,True,NaN,0.00,45
5517,Syria,1982,10.00,532.00,3391.00,37.00,144.00,1107.67,nan,True,True,True,True,0.00,180
4266,Pakistan,1998,2.00,530.00,1047.00,45.67,127.67,680.67,nan,True,True,True,True,0.00,140
5055,South Korea,1950,0.00,528.00,3500.00,2.00,4.00,0.00,nan,True,True,NaN,NaN,0.00,171
2187,Greece,1974,105.00,525.00,3789.00,0.67,37.67,157.00,nan,NaN,True,True,True,0.00,70
2475,India,1983,172.00,525.00,3712.00,28.00,805.00,3175.00,nan,True,True,True,True,0.00,81
1733,Egypt,1988,20.00,525.00,3749.00,12.00,132.67,535.67,nan,NaN,True,True,True,0.00,55
2755,Israel,1975,1503.00,522.00,3195.00,12.67,417.00,3173.33,nan,True,True,True,True,0.00,86
1328,Cuba,1961,0.00,516.00,225.00,0.00,198.33,558.00,nan,True,True,True,True,0.00,45
3283,Libya,1977,40.00,514.00,140.00,34.33,1284.00,5623.33,nan,NaN,True,True,True,0.00,103
514,Belgium,1979,1.00,514.00,3825.00,41.00,11.00,254.00,nan,NaN,True,True,True,0.00,15
4797,Saudi Arabia,2009,975.00,513.00,3098.00,268.67,87.67,971.00,617047.00,NaN,True,True,True,6217278.00,159
2667,Iraq,1983,93.00,503.00,1966.00,6.33,2874.33,3364.33,nan,True,True,True,True,0.00,84
2754,Israel,1974,38.00,503.00,3800.00,6.67,314.67,1978.00,nan,True,True,True,True,0.00,86
150,Angola,1999,0.00,503.00,56.00,2.00,29.00,17.33,nan,True,True,True,True,0.00,3
2492,India,2001,46.00,502.00,2541.00,168.33,405.00,1807.67,1652059.00,True,True,True,True,292489.33,81
2400,Hungary,1972,0.00,500.00,106.00,0.00,27.00,1666.67,nan,NaN,True,True,True,0.00,79
2497,India,2006,38.00,496.00,196.00,52.33,145.33,1311.00,4795781.00,True,True,True,True,4059848.33,81
2747,Israel,1967,476.00,494.00,193.00,142.33,117.33,183.33,nan,True,True,True,True,0.00,86
3276,Libya,1970,150.00,489.00,696.00,0.00,36.00,257.67,nan,NaN,True,True,True,0.00,103
127,Angola,1975,1.00,481.00,1906.00,0.00,19.00,0.00,nan,True,True,NaN,NaN,0.00,3
4222,Pakistan,1954,2.00,480.00,206.00,2.00,73.00,0.00,nan,NaN,True,True,NaN,0.00,140
3662,Morocco,1978,0.00,479.00,454.00,14.00,118.67,2204.67,nan,True,True,True,True,0.00,123
4507,Poland,1960,0.00,478.00,1750.00,333.33,135.33,66.67,nan,NaN,True,True,True,0.00,148
1705,Egypt,1960,163.00,476.00,500.00,66.67,129.00,83.33,nan,NaN,True,True,True,0.00,55
486,Belgium,1950,0.00,473.00,50.00,0.00,101.33,0.00,nan,NaN,True,True,NaN,0.00,15
4060,North Korea,1976,0.00,470.00,4000.00,11.00,61.33,6866.67,nan,NaN,True,True,True,0.00,137
2508,India,2017,131.00,466.00,638.00,229.33,281.33,704.00,3700000.00,NaN,True,True,True,8547505.67,81
3844,Netherlands,1979,14.00,465.00,300.00,7.33,12.33,2041.67,nan,NaN,True,True,True,0.00,129
4771,Saudi Arabia,1982,224.00,464.00,3582.00,9.00,40.00,3553.33,nan,NaN,True,True,True,0.00,159
2773,Israel,1993,10.00,460.00,353.00,0.00,39.00,319.00,nan,True,True,True,True,0.00,86
1699,Egypt,1954,0.00,459.00,300.00,0.00,81.67,0.00,nan,NaN,True,True,NaN,0.00,55
6279,Vietnam,1979,2.00,450.00,2946.00,0.00,67.33,686.67,nan,True,True,True,NaN,0.00,203
86,Algeria,1977,3.00,447.00,715.00,7.33,88.67,458.33,nan,NaN,True,True,True,0.00,2
532,Belgium,2005,0.00,442.00,277.00,11.33,2.33,100.00,nan,NaN,True,True,True,0.00,15
487,Belgium,1951,0.00,438.00,42.00,0.00,259.00,16.67,nan,NaN,True,True,NaN,0.00,15
3818,Netherlands,1950,0.00,437.00,88.00,10.00,63.33,10.67,nan,NaN,True,True,NaN,0.00,129
1150,China,2002,1.00,437.00,680.00,106.67,46.67,443.67,123659.00,NaN,True,True,True,24514.67,37
2995,Jordan,1999,0.00,430.00,150.00,1.33,16.00,60.67,nan,NaN,True,True,True,0.00,90
4764,Saudi Arabia,1975,4.00,430.00,12534.00,0.00,120.33,2067.00,nan,NaN,True,True,True,0.00,159
776,Bulgaria,1978,0.00,429.00,1950.00,3.00,44.67,1156.67,nan,NaN,True,True,True,0.00,26
2735,Israel,1955,87.00,428.00,1000.00,0.00,190.67,70.00,nan,True,True,True,NaN,0.00,86
6367,Yugoslavia,1977,0.00,425.00,5650.00,16.67,15.67,5623.33,nan,NaN,True,True,True,0.00,205
132,Angola,1980,17.00,419.00,368.00,13.67,90.33,133.33,nan,True,True,True,NaN,0.00,3
2643,Iraq,1958,0.00,418.00,500.00,0.00,12.33,8.00,nan,True,True,True,True,0.00,84
5856,Turkey,1993,368.00,415.00,512.00,806.33,501.67,1631.67,nan,True,True,True,True,0.00,190
1749,Egypt,2004,40.00,412.00,203.00,88.67,170.67,308.33,1304172936.00,NaN,True,True,True,1312335408.00,55
5215,Spain,1970,7.00,411.00,1084.00,0.00,4.33,47.33,nan,NaN,True,True,True,0.00,172
4505,Poland,1957,0.00,406.00,200.00,39.00,152.00,506.67,nan,NaN,True,True,True,0.00,148
2663,Iraq,1979,75.00,406.00,1750.00,10.00,447.00,870.00,nan,True,True,True,True,0.00,84
4804,Saudi Arabia,2016,6.00,406.00,5225.00,52.33,923.67,11863.00,15000.00,NaN,True,True,True,263815.00,159
3630,Mongolia,1981,0.00,404.00,3000.00,0.00,4.67,16.67,nan,NaN,True,True,True,0.00,121
1727,Egypt,1982,88.00,402.00,1620.00,8.33,314.67,2986.00,nan,NaN,True,True,True,0.00,55
4395,Peru,1973,0.00,402.00,415.00,0.67,32.33,385.00,nan,NaN,True,True,True,0.00,146
6034,United Kingdom,2003,1.00,401.00,6174.00,8.00,17.00,5324.00,7000.00,True,True,True,True,22731.67,197
5165,Yemen,1980,0.00,400.00,336.00,0.00,0.00,0.00,nan,True,NaN,NaN,True,0.00,204
5546,Taiwan,1951,0.00,399.00,60.00,0.00,0.00,0.00,nan,NaN,NaN,NaN,NaN,0.00,181
4568,Portugal,1960,12.00,399.00,400.00,0.00,25.67,0.00,nan,NaN,True,True,True,0.00,149
2471,India,1979,18.00,396.00,50350.00,11.33,334.67,318.00,nan,True,True,True,True,0.00,81
2442,India,1950,0.00,395.00,160.00,0.00,47.67,0.00,nan,True,True,NaN,NaN,0.00,81
1715,Egypt,1970,30.00,394.00,50.00,24.67,802.00,5338.33,nan,True,True,True,True,0.00,55
1963,France,1956,0.00,394.00,232.00,42.00,434.00,0.00,nan,True,True,True,True,0.00,63
2791,Israel,2011,2.00,390.00,160.00,40.00,14.33,1533.33,3424587932.00,True,True,True,True,2768309017.67,86
3846,Netherlands,1981,0.00,387.00,949.00,12.00,170.67,1906.33,nan,NaN,True,True,True,0.00,129
2467,India,1975,202.00,385.00,100.00,160.00,139.33,3862.33,nan,NaN,True,True,True,0.00,81
4544,Poland,2003,661.00,383.00,3592.00,14.33,74.00,242.00,41807116.00,NaN,True,True,True,16400186.67,148
5142,Vietnam,1964,0.00,381.00,100.00,0.00,0.00,0.00,nan,NaN,NaN,True,True,0.00,203
2218,Greece,2005,6.00,379.00,100.00,22.67,157.33,731.00,1163000.00,NaN,True,True,True,13928279.67,70
926,Canada,1952,0.00,377.00,7.00,18.00,598.67,9.33,nan,NaN,True,True,NaN,0.00,32
144,Angola,1993,0.00,376.00,23.00,2.00,3.33,50.00,nan,True,True,True,True,0.00,3
4233,Pakistan,1965,0.00,372.00,625.00,9.00,12.00,1386.33,nan,True,True,True,True,0.00,140
4108,Norway,1951,0.00,372.00,480.00,0.00,50.00,0.00,nan,NaN,True,NaN,NaN,0.00,138
6251,Venezuela,2009,0.00,369.00,1516.00,32.67,30.00,1092.33,636660.00,NaN,True,True,True,575837.67,202
5141,Vietnam,1963,0.00,368.00,125.00,0.00,0.00,0.00,nan,NaN,NaN,True,True,0.00,203
2759,Israel,1979,0.00,367.00,7304.00,58.67,107.67,1065.33,nan,True,True,True,True,0.00,86
4051,North Korea,1967,0.00,365.00,550.00,0.00,606.67,1113.33,nan,NaN,True,True,True,0.00,137
6269,Vietnam,1968,30.00,360.00,400.00,0.00,0.00,0.00,nan,True,NaN,NaN,True,0.00,203
4264,Pakistan,1996,2.00,360.00,2020.00,47.67,53.00,51.00,nan,True,True,True,True,0.00,140
3823,Netherlands,1955,3.00,359.00,198.00,27.00,336.33,0.00,nan,NaN,True,True,True,0.00,129
5514,Syria,1979,99.00,357.00,500.00,0.00,1511.33,3126.67,nan,True,True,True,True,0.00,180
1726,Egypt,1981,8.00,357.00,3840.00,14.33,197.67,2175.33,nan,NaN,True,True,True,0.00,55
6000,United Kingdom,1964,3.00,352.00,50.00,0.00,40.33,2034.00,nan,NaN,True,True,True,0.00,197
5567,Taiwan,1972,0.00,349.00,96.00,2.33,48.67,29.67,nan,NaN,True,True,True,0.00,181
6099,United States,2006,6.00,348.00,295.00,43.33,52.67,862.33,nan,True,True,True,True,0.00,198
3601,Mexico,2014,56.00,345.00,4.00,10.00,379.00,1.00,205653013.00,NaN,True,True,True,279143301.00,117
1738,Egypt,1993,0.00,343.00,354.00,32.00,316.33,841.00,nan,True,True,True,True,0.00,55
367,Azerbaijan,2010,0.00,335.00,202.00,16.67,39.00,319.33,5904648.00,NaN,True,True,True,28568694.67,9
505,Belgium,1970,0.00,335.00,480.00,0.00,180.33,25.00,nan,NaN,True,True,True,0.00,15
5164,Yemen,1979,0.00,331.00,2347.00,0.00,0.00,0.00,nan,True,NaN,NaN,True,0.00,204
2504,India,2013,20.00,330.00,25261.00,321.00,145.00,4276.67,7045324.00,True,True,True,True,7705088.67,81